# Generated by Django 5.0.4 on 2024-05-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('cash_flow', models.JSONField()),
            ],
        ),
    ]
